# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
      docker:
        - image:  microsoft/dotnet 
      steps:
        - checkout
        - run: 
            name: get dependencies
            command: dotnet restore ./src
        - run: 
            name: build
            command: dotnet build ./src
